# Generated by Django 4.2.3 on 2023-08-02 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_favourite_items_order_userprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='slug',
        ),
        migrations.AlterField(
            model_name='items',
            name='item_id',
            field=models.TextField(),
        ),
    ]
