# Generated by Django 4.2.3 on 2023-07-30 14:03

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='slug',
            field=autoslug.fields.AutoSlugField(default='none', editable=False, populate_from='name'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='category',
            name='slug',
            field=autoslug.fields.AutoSlugField(default='None', editable=False, populate_from='name'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='slug',
            field=autoslug.fields.AutoSlugField(default=0, editable=False, populate_from='name'),
            preserve_default=False,
        ),
    ]
