# Generated by Django 4.2.3 on 2023-08-03 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_alter_items_item_id_alter_items_item_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='items',
            name='item_id',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='items',
            name='item_quantity',
            field=models.IntegerField(default=1),
        ),
    ]
