# Generated by Django 4.2.3 on 2023-08-06 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_rename_order_id_order_user_id_order_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='Status',
            field=models.CharField(default=None, max_length=20),
            preserve_default=False,
        ),
    ]
