# Generated by Django 4.2.3 on 2023-08-08 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='Status',
            field=models.CharField(choices=[('In Progress', 'In Progress'), ('Cancelled', 'Cancelled'), ('Completed', 'Completed')], default='In Progress', max_length=20),
        ),
    ]
