# Generated by Django 4.2.3 on 2023-08-08 05:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_alter_order_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='Address',
        ),
    ]
