# Generated by Django 4.2.3 on 2023-08-08 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0018_remove_order_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='Date',
        ),
        migrations.AddField(
            model_name='order',
            name='Address',
            field=models.TextField(default=None),
            preserve_default=False,
        ),
    ]
