# Generated by Django 4.2.3 on 2023-08-08 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0019_remove_order_date_order_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='Status',
            field=models.CharField(choices=[('In Progress', 'In Progress'), ('Cancelled', 'Cancelled'), ('Completed', 'Completed')], default='In Progress', max_length=20),
        ),
    ]
