# Generated by Django 4.2.3 on 2023-08-10 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0022_alter_order_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='name',
            field=models.CharField(db_index=True, max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(db_index=True, max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='favourite',
            name='favourite_id',
            field=models.IntegerField(db_index=True),
        ),
        migrations.AlterField(
            model_name='items',
            name='item_id',
            field=models.IntegerField(db_index=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.FloatField(db_index=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user_id',
            field=models.IntegerField(db_index=True),
        ),
    ]
